project:
  type: book
  output-dir: docs
  
book:
  title: "Data Analysis & Information Extraction"
  reader-mode: true
  favicon: cunef_logo.png
  
  page-footer:
    left: |
      Data Analysis & Information Extraction - <a href="https://cunef.edu/">CUNEF Universidad</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
  
    
    - part: 01_introduction.qmd
      chapters: 
        - 01_01_r_software.qmd
        - 01_02_rstudio.qmd
        - 01_03_getting_started.qmd
        - 01_04_rmarkdown.qmd
        - 01_05_packages.qmd
        
    - part: 02_programming.qmd
      chapters:
        - 02_01_first_concepts.qmd
        - 02_02_objects.qmd
        - 02_03_dataframes.qmd
        - 02_04_structures.qmd
        
    - part: 03_tidyverse.qmd
      chapters:
        - 03_01_tibbles.qmd
    
    - part: 04_visualization.qmd
      chapters:
        - 04_01_plots.qmd
        - 04_02_aesthetics.qmd
        - 04_03_facets.qmd
        - 04_04_datatypes.qmd
        - 04_05_customization.qmd
        
    - part: 05_transformation.qmd
      chapters:
        - 05_01_basic_manipulation.qmd
        - 05_02_filtering.qmd
        - 05_03_aggregations.qmd
        
    - part: 06_eda.qmd
      chapters: 
        - 06_01_variation.qmd
        - 06_02_covariance.qmd
    
    - part: 07_reading.qmd
    
    - part: 08_arrange.qmd
    
    - part: 09_clean.qmd

    - part: 10_modelling.qmd
      chapters: 
        - 10_01_models.qmd
        - 10_02_linear_regression.qmd
        - 10_03_inference.qmd
  
format:
  html:
    code-line-numbers: true
    theme:
      - cosmo
    