# Welcome {.unnumbered}

This is the book website for the **Data Analysis & Information Extraction** course at **CUNEF Universidad**.

The book covers all course contents and provides full explanation of the different topics. You will find explanations and examples to guide your learning.

The book is structured following the course schedule. Now we explain the content of each chapter with references to each of the main units the course is structured.

+---------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Unit                                  | Chapters                         | Summary                                                                                                                                |
+=======================================+==================================+========================================================================================================================================+
| **Unit 1**: Programming with R        | 01 - Introduction to Programming | Configuration and introduction R and RStudio software that we will use for developing with R during the course.                        |
|                                       |                                  |                                                                                                                                        |
|                                       | 02 - Programming with R          | Explaining all basic concepts of the R language, teaching the different data types, main functions and programming structures.         |
+---------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 2**: Exploratory Data Analysis | 03 - Tidyverse                   | Introduction to the Tidyverse package for data analysis.                                                                               |
|                                       |                                  |                                                                                                                                        |
|                                       | 04 - Visualization               | Explaining the main tools for creating plots and rules to decide how to represent data.                                                |
|                                       |                                  |                                                                                                                                        |
|                                       | 05 - Transform Data              | Basic transformation tools for manipulate data and work with it.                                                                       |
|                                       |                                  |                                                                                                                                        |
|                                       | 06 - Exploratory Data Analysis   | Know the steps for properly analyze data and understand the information.                                                               |
+---------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 3**: Data Wrangling            | 07 - Reading Data                | Know the main tools for importing data in R.                                                                                           |
|                                       |                                  |                                                                                                                                        |
|                                       | 08 - Arrange Data                | Understand how to perform advance transformation to clean and use the data properly for the different analysis needs.                  |
|                                       |                                  |                                                                                                                                        |
|                                       | 09 - Clean Data                  |                                                                                                                                        |
+---------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Unit 4**: Modelling                 | 10 - Modelling                   | Understand the basic concepts of data modelling to make predictions. Focus on Linear Regression models. Now how to obtain estimations. |
+---------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
