{
  "hash": "948831e622ddb8c235d0a7c4bbf61dde",
  "result": {
    "engine": "knitr",
    "markdown": "# Inference {.unnumbered}\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nWe need to understand some concepts first...\n\n* **Population**: Group of elements to study\n* **Parameter**: Numeric amount originated from the population, normally unknown. \n\nIf we have data about each element of the **population** we could calculate the population **parameter**. \n\nBut this is not possible in most of the cases. For this reason we work with...\n\n* **Sample**: A subset of our population of interest.\n* **Statistic**: Numeric amount originated from the sample. \n\nIf the **sample** represents correctly the population we could use probability and statistical inference to obtain conclusions applicable to the whole population. \n\n## Statistical Inference\n\n**Statistical Inference** is the process that allows, through data, obtain conclusions and apply them to the whole population where the sample was originated. \n\n* **Estimation**, use the sample to estimate a possible interval of values for a given population parameter unknown. \n\n* **Hypothesis Contrast**, evaluate if the given sample shows an evidence of the application of a given affirmation about the population.\n\nWe will work with **estimation** here. \n\nFor the rest of this chapter we will work with a sample data to help us explain the concepts and a case: **Average price of an Airbnb in València**\n\nWe have obtained the data from València Airbnb prices thanks to [Inside Airbnb](https://insideairbnb.com/valencia/) data repository that scrapped all listings from the website on the 22nd of June 2024. \n\n**Population for the analysis:** All airbnb' houses/apartments  with at least 10 reviews in València. \n\n**Goal Paremeter:** Average price per night in those airbnbs.\n\nWhich is the average price for an airbnb with at leat 8 reviews in the city of Valéncia at the month of June? \n\nWe are going to use a random sample data with 50 airbnb locations with the price per night value informed.\n\n## Point Estimation\n\nA **point estimator** is a value computed from the sample to serve as the \"best estimation\" for the population parameter. \n\nOur point estimator for the average price per night will be the average obtained from the sample:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"data/vlc_listings_50.csv\")\ndata %>% \n  summarise(mean_price = mean(price))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  mean_price\n       <dbl>\n1       138.\n```\n\n\n:::\n:::\n\n\n\n\nNow we can see our point estimator and the sample represented with an histogram\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data) +\n  geom_histogram(aes(x=price),bins=10,fill=\"lightgrey\",color=\"black\") +\n  geom_vline(xintercept = 137.98, color=\"red\") +\n  geom_text(x=150, y = 15, label = \"137.9\", size = 4) +\n  ggtitle(\"AirBnB price distribution for June 2024 in València\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\nPoint estimators are useful when we are trying to find a general value to define a parameter, but they can be not representative and highly affected by the distribution of the sample values. We can provide a range of values where the parameter can be found. \n\n* If we provide only a single value (point estimation), we can fail trying to find the exact parameter for the population.\n\n* If we provide a range of values, we have more probabilities of having the parameter inside the range of values we found. \n\n## Confidence Intervals\n\nFor building a confidence interval for the population parameter, we need to create a rank of possible values around the observed sample's average. \n\nIt is important to note that the random samples, will be different between them. This means if we take a another random sample of more 50 listings about AirBnb in València, it is possible not to obtain the same price average. \n\n**There is a variability in the sample average.**\n\nFor building a confidence interval, we need to measure this variability. This will give us on how much we can expect our sample average to variate from each sample. \n\n:::: .calloit-caution\nEx 1: We divide the class in two groups and we ask each student their height. Then we compute the average height for each group. Will you expect them to be the same, similar or different?\n\nEx 2: We take 50 students randomly and looks 5 of them write with the left hand. If you take another random sample of 50 students. How many of them will you expect to be left-handed? Will you be surprised if only 3 of them are left-handed? And if they were 40 this time?\n::::\n\n### How to measure variability?\n\nWe can measure variability of the sample values with different approaches:\n\n* **Simulation**: we can use re-sampling techniques or \"bootstrap\" to find different values for the same metric. \n\n* **Theory**: using the Central Limit Theorem (Normal Distribution)\n\n\n## Bootstrap\n\n**Bootstrap** is a re-sample technique used for measuring the variance of an estimation. \n\nWe will use it for estimating the population parameter using only the given sample. \n\nIt uses the same principles of the statistical inference so it is considered an alternative. \n\n![](pictures/Illustration_bootstrap.png)\n\n\n###  Bootstrap Procedure\n\n1. Take a **bootstrap sample**, a random sample **with replacement** from the original sample, **with the same size** of the original sample. \n\n2. Compute the **bootstrap statistic**: the statistic we want to compute (average, median, correlation, ...) using the bootstrap sample. \n\n3. Repeat steps 1 and 2 multiple times to create a **bootstrap distribution** - a distribution of bootstrap statistics. \n\n4. Compute the confidence interval limits of XX% as the region that has the XX% of the bootstrap distribution. \n\n#### Step by step\n \n**Step 1.** Take a **bootstrap sample**, a random sample **with replacement** from the original sample, **with the same size** of the original sample. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nindices <- sample(1:nrow(data), 50, replace = T)\nboot_samp_1 <- data %>% \n  select(price) %>% \n  slice(indices)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(boot_samp_1) +\n  geom_histogram(aes(x=price),bins=10,fill=\"lightgrey\",color=\"black\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Step 2.** Compute the **bootstrap statistic**: the statistic we want to compute (the average price in this case) using the bootstrap sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean1 <- round(mean(boot_samp_1$price), 2)\nggplot(boot_samp_1) +\n  geom_histogram(aes(x=price),bins=10,fill=\"lightgrey\",color=\"black\") +\n  geom_vline(xintercept = mean1, color=\"red\") +\n  geom_text(x=150, y = 15, label = mean1, size = 4) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n \n**Step 3.** Repeat steps 1 and 2 multiple times to create a **bootstrap distribution**\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\nIn this case we have make 500 bootstrap re-samples and then compute the average for each one. What we do finally is represent all the averages in an histogram plot:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-12-1.png){width=70%}\n:::\n:::\n\n\n\n\nHere we can compare the original sample and the distribution of bootstrap means. \n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Step 4.** Compute the limits of the bootstrap interval using the percentiles of the bootstrap distribution. \n\n\n\n\n```{ojs}\n//| panel: sidebar\n//| echo: false\nd3 = require(\"d3@7\")\n\nviewof confidence = Inputs.range(\n  [0, 100], \n  {value: 95, step: 1, label: \"Confidence%:\"}\n)\n\nlowerBound = d3.quantile(boot_plot.boot_mean,(1-confidence/100)/2)\n\nupperBound = d3.quantile(boot_plot.boot_mean,confidence/100+(1-confidence/100)/2)\n\n```\n\n```{ojs}\n//| panel: fill\n//| echo: false\n\nPlot.plot({\n  y: {\n    grid: true\n  },\n  marks: [\n    Plot.rectY(\n      boot_plot.boot_mean,\n      Plot.binX(\n        { \n          y: \"count\"\n        },{\n        fill: \"#ffdad8\",\n        \n        }\n      )\n    ),\n      Plot.ruleX([lowerBound]),\n      Plot.ruleX([upperBound])\n  ]\n})\n```\n\n\n\n\n\n## `infer` package\n\nInfer package help us do an inferential analysis like bootstraping but using the tidyverse ecosystem sintax. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(infer)\n```\n:::\n\n\n\n\n\n### Choose a seed\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n```\n:::\n\n\n\n\nWhen doing analysis, simulations and sampling techniques it is recommended to make them replicable. \n\n`set.seed()` is an R base function that help us establish a common starting point on your machine, helping you control simulations and making them replicable. \n\nThis means that if use the same seed, you will guarantee that each time you run your code you will get the same results. \n\n\n### Generate Bootstrap averages\n\n#### `specify()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2,3\"}\ndata %>% \n  # specifiy the variable of interest\n  specify(response = price)\n```\n:::\n\n\n\n\nWith `specify()`, we will tell infer which is the variable we will use to make the re-sampling, our objective variable to obtain the bootstrap mean.\n\n\n#### `generate()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"4,5\"}\ndata %>% \n  # specifiy the variable of interest\n  specify(response = price) %>% \n  # generate 15000 bootstrap samples\n  generate(reps = 1500, type = \"bootstrap\")\n```\n:::\n\n\n\n\nWith `generate()`, we will tell infer which is the number of re-samplings we want to do, and the technique we want to use. In this case Bootstrap re-sampling.\n\n#### `calculate()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"6,7\"}\ndata %>% \n  # specifiy the variable of interest\n  specify(response = price) %>% \n  # generate 15000 bootstrap samples\n  generate(reps = 1500, type = \"bootstrap\") %>% \n    # calculate the statistic of each bootstrap sample\n  calculate(stat = \"mean\")\n```\n:::\n\n\n\n\nWith `calculate()`, we will tell infer which is the metric we want to compute for each sample, so we can get the metric distribution. In this case we choose the mean, but we can select other kind of metrics, like the median for example.\n\n:::: .callout-caution\n\n# Full Example of Bootstrap computation\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_reps <- 100\n\n# save resulting bootstrap distribution\nboot_dist <- data %>%\n  # specify the variable of interest\n  specify(response = price) %>% \n  # generate 100 bootstrap samples\n  generate(reps = num_reps, type = \"bootstrap\") %>% \n  # calculate the statistic of each bootstrap sample\n  calculate(stat = \"mean\")\n\nboot_dist %>% glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 2\n$ replicate <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ stat      <dbl> 141.78, 137.74, 126.60, 142.64, 142.86, 132.52, 144.26, 148.…\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n## Visualize the distribution\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = boot_dist, aes(stat)) +\n  geom_histogram(binwidth = 5, color = \"darkred\", fill = \"pink\") +\n  labs(x = \"\", y = \"\", title = \"Bootstrap distribution of sample means\") +\n  scale_x_continuous(breaks = seq(0, 250, by = 50)) + \n  xlim(0, 250) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n## Computing Confidence Intervals\n\nA confidence interval of 95% means that it contains the 95% central possible values of the bootstrap distribution. For obtaining this 95%, we need to exclude the other 5% of the sample. \n\nAs it is a 95% central, means that we need to exclude 2.5% of each side (5% / 2) of the distribution. \n\n![](pictures/Interval_Diagram.png)\n\nFor making this computation with **dplyr**:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nci <- boot_dist %>%\n  summarise(lower_b = quantile(stat, 0.025), \n            upper_b = quantile(stat, 0.975))\nci\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_b upper_b\n    <dbl>   <dbl>\n1    122.    158.\n```\n\n\n:::\n:::\n\n\n\n\n## Visualizing Confidence Intervals\n\n### Option 1\n\nUsing ggplot geometric `geom_vline()` to mark the limits of the interval:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1,3,4,5,6\"}\nggplot(data = boot_dist, mapping = aes(x = stat)) +\n  geom_histogram(binwidth = 5, alpha = .5) +\n  geom_vline(xintercept = ci$lower_b,\n             color = \"steelblue\", lty = 2, size = 1) + \n  geom_vline(xintercept = ci$upper_b,\n             color = \"steelblue\", lty = 2, size = 1) +\n  labs(title = \"Bootstrap distribution of the average price.\",\n       subtitle = \"with CI of 95%\",\n       x = \"Averages\", y = \"Number\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\n### Option 2\n\nUsing `visualize` function together with `shade_confidence_interval` that prints the intervals passed. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1,2\"}\nvisualize(boot_dist) +\n  shade_confidence_interval(endpoints = ci)+\n  labs(title = \"Bootstrap distribution of the average price.\",\n       subtitle = \"with CI of 95%\",\n       x = \"Averages\", y = \"Number\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09_03_inference_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\n\n## Interpreting the Confidence Interval\n\nOur Confidence Interval of 95% is [122, 158].\n\n* The population parameter can be or not in our interval. There is no a \"probability of 95%\" for it to be in an specific interval.\n\n* Bootstrap distribution computes the variance of the parameter based on sample of the population. And the idea that the origin data comes from a sample, means that if if we change the sample the interval with a confidence of 95% can change. \n\n* All that we can say, is that *if we take independent samples of the population and compute a 95% CI for the average for each one, we expect that the 95% of these intervals to contain the population average. \n\n* But we are not sure enough that the population parameter is inside the interval.\n\n--------\n**We have a 95% confidence that the average price of an apartment in València for  June is between 122 and 158 euros.**\n--------\n",
    "supporting": [
      "09_03_inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script type=\"ojs-define\">\n{\"contents\":[{\"name\":\"boot_plot\",\"value\":{\"boot_mean\":[128.94,115.64,130.38,130.48,134.18,133.88,143.02,131.22,141.74,122.82,130.2,132.06,149.86,154.66,142.56,136.72,140.74,127.66,140.36,138.16,148.92,125.48,138.18,127.12,147.24,132.04,148.84,126.18,132.8,145.9,150.94,153.84,150.28,151.18,147.28,140.72,137.2,138.28,129.26,133.16,128.52,154.62,132.5,146.24,138.5,130.38,128.34,127.26,150.02,123.02,127.28,128.06,130.68,128.1,146.12,120.9,137.08,138.92,137.04,153.62,126.24,137.54,120.74,119.02,133.56,134.08,125.34,132.42,143.26,140.92,144.76,129.64,137.84,140.52,124.44,140.44,146.18,141.98,143.66,135.32,141.42,147.52,157.08,131.72,137.48,153.42,122.46,126.04,138.78,121.56,147.32,138.3,153.2,131.64,134.84,128.6,139.6,154.26,137.72,113.44,150.18,166.24,137.74,126.08,125.02,139.18,137.26,159.3,141.04,138.16,156.74,134.16,157.42,119.64,153.62,156,127.78,121.48,128.94,147.34,150.84,142.14,141.78,124.96,143.78,132.76,150.02,140.62,147.84,135.94,142.06,133.4,121.96,148.32,127.92,119.52,141.56,146.86,144.88,150.94,135.06,132.3,126.7,121.56,123.86,126.74,137.4,143.64,128.2,128.18,161.18,163.06,137.4,125.86,130.08,138.42,150.58,145.94,112.94,143.86,156.3,133,141.22,118.6,128.08,149.06,139.2,139.34,149.58,148.66,133.18,138.14,131.1,138.96,143.62,136.78,127.32,134.86,137.08,143.04,143.12,142.8,139.62,130.1,136.2,129.42,127.9,143.42,124.5,142.74,130.28,141.86,127.04,126.86,143.4,137.02,126.84,133.98,140.6,132.72,142.74,115.36,130.14,149.26,124,144.5,132.5,135.12,138.56,145.54,132.54,130.58,125.16,124.04,137.92,123.7,132.96,146.82,140.3,137.38,148.04,142.18,142.62,130,140.36,152.28,117.74,123.06,136.2,113.82,118.18,131.66,138.4,124.96,146.18,136.06,114.28,153.06,157.82,127.8,129.18,137.98,133.1,127.64,141.9,143.7,139.2,157.5,140.3,132.7,152.02,137.18,143.64,135.24,138.7,152.9,135.1,146.3,137.56,154.84,142.36,150.8,147,137.36,149.64,144.1,145.22,158.12,143.36,124.86,150.24,132.78,155.82,148.38,138.22,147.14,137.78,126.96,127.84,134.12,144.58,162.1,132.26,128.7,128.02,143.78,141.3,136.38,148.46,151.3,141.24,128.36,142.48,120.7,132.94,145.7,128.82,131.64,138.36,122.34,161.82,126.26,150.62,137.16,138.38,128.3,151.42,140.98,125.66,126.62,132.28,157.74,140.64,138.3,138.22,148.38,125.16,137.38,134.54,120.78,162.34,130.04,129.02,154.42,168.48,127.86,128.92,144.78,138.24,128.78,133.74,130.06,144.94,138.22,146.32,134.64,143.1,139.34,137.28,111.34,136.42,136.14,141.74,138.78,122.68,126.52,140.64,146.24,138.36,128.62,141.7,156.22,135.58,147.58,132.1,133.78,134.18,155.92,151.34,114.44,118.66,148.6,152.5,148.38,120.88,124.86,124.8,121.1,134.42,136.46,135.7,151.34,135.96,134.4,135.26,143.66,132.78,146.94,132.08,137.28,162.76,145.76,156.54,147.26,146.58,135.06,161.14,105.96,124.92,138.32,143.58,153.94,129.44,135.78,162.6,127.68,146.64,125.36,168.2,158.36,171.78,119.64,139.1,133.14,154.82,138.96,135.54,141.16,141.22,140.1,157.26,155.66,131.92,132.02,133.52,132.22,125.64,148.58,153.74,121.2,136.88,166.5,147.42,143.66,136.16,127.04,125.62,149.64,133.72,125,127.6,140.94,143.54,142.94,157.32,141.8,139.02,131.04,138.78,145.34,148.28,120.26,158.62,139.92,132.16,148.6,128.48,144.8,133.34,122.58,119.14,138.52,151.36,135.82,115.46,133.82,166.4,144.42,131.58,141.12,148.74,141.42,141.84,127.5,131.68,123.24,141.72,129.92,161.84,121.76,138.42,159.56,136.96,147.26,141.32,125.42,144.6,148.76,124.26,126.02,166.52,137.6,143.88,138.38,132.76,160.74,130.48,137.1,145.78,147.58,139.2,131.9,135.8,134.46,138.18,141.64,127.96,157.52,128.7,159.9]}}]}\n</script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}